import time
from selenium import webdriver
driver=webdriver.Ie(executable_path= '../Exercise/drivers/IEDriverServer.exe')
driver.maximize_window()
time.sleep(2)
driver.get('https://opensource-demo.orangehrmlive.com/')
print(driver.title)
print(driver.current_url)
a1=driver.find_element_by_id('txtUsername')
a1.send_keys('satee143')
a2=driver.find_element_by_id('txtPassword')
a2.send_keys('9989884111')
btn= driver.find_element_by_id('btnLogin')
btn.click()
a1=driver.find_element_by_id('txtUsername')
a2=driver.find_element_by_id('txtPassword')
a2.send_keys('9989858000')
a1.send_keys('dusa.skumar')
print(a1.get_attribute('value'))
print(a2.get_attribute('value'))
btn= driver.find_element_by_id('btnLogin')
time.sleep(3)
a1.clear()
a2.clear()
time.sleep(3)
a1.send_keys('Admin')
a2.send_keys('admin123')
btn.click()
driver.fullscreen_window()
menu=driver.find_element_by_xpath('//*[@id="welcome"]')
menu.click()
print(menu.text)
driver.find_element_by_id('aboutDisplayLink').click()
# logout=driver.find_element_by_css_selector('#welcome-menu > ul > li:nth-child(2) > a')
# logout.click()
