from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path='../drivers/chromedriver.exe')
# driver.maximize_window()
# time.sleep(2)
# driver.get('https://opensource-demo.orangehrmlive.com/')
# print(driver.title)
# print(driver.current_url)
# a1=driver.find_element_by_id('txtUsername')
# a1.send_keys('satee143')
# a2=driver.find_element_by_id('txtPassword')
# a2.send_keys('9989884111')
# driver.get('http://google.com')
# driver.back()
# time.sleep(3)
# btn= driver.find_element_by_id('btnLogin')
# btn.click()
# a1=driver.find_element_by_id('txtUsername')
# a2=driver.find_element_by_id('txtPassword')
# a2.send_keys('9989858000')
# a1.send_keys('dusa.skumar')
# print(a1.get_attribute('value'))
# print(a2.get_attribute('value'))
# print(a2.get_attribute('type'))
# btn= driver.find_element_by_id('btnLogin')
# time.sleep(3)
# a1.clear()
# a2.clear()
# time.sleep(3)
# a1.send_keys('Admin')
# a2.send_keys('admin123')
# btn.click()
# driver.fullscreen_window()
# menu=driver.find_element_by_xpath('//*[@id="welcome"]')
# menu.click()
# print(menu.text)
#logout=driver.find_element_by_link_text('Logout').click()
#logout.
driver.get('https://mail.rediff.com/cgi-bin/login.cgi')

driver.find_element_by_name('proceed').click()
print(driver.switch_to.alert.text)
driver.switch_to.alert.accept()
#print(popup.text)
driver.find_element_by_id('login1').send_keys('satee143')
driver.find_element_by_id('password').send_keys('dusa143')